accent = "#00D4FF"
cursor = "#00D4FF"
foreground = "#E8E8E8"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#00D4FF"

color0 = "#000000"
color1 = "#CC3333"
color2 = "#33CC66"
color3 = "#CCCC33"
color4 = "#3388CC"
color5 = "#8844AA"
color6 = "#00D4FF"
color7 = "#C0C0C0"
color8 = "#404040"
color9 = "#FF4444"
color10 = "#44FF77"
color11 = "#FFFF44"
color12 = "#44AAFF"
color13 = "#AA66CC"
color14 = "#44FFFF"
color15 = "#E8E8E8"
