accent = "#008BAD"
cursor = "#008BAD"
foreground = "#000000"
background = "#FFFFFF"
selection_foreground = "#FFFFFF"
selection_background = "#008BAD"

color0 = "#000000"
color1 = "#CC3333"
color2 = "#1A8A44"
color3 = "#8A8A00"
color4 = "#2266AA"
color5 = "#773399"
color6 = "#008BAD"
color7 = "#C0C0C0"
color8 = "#666666"
color9 = "#FF4444"
color10 = "#22BB55"
color11 = "#AAAA00"
color12 = "#3388CC"
color13 = "#9944BB"
color14 = "#00AACC"
color15 = "#FFFFFF"
